mock_db_data = [
    {
        "name": "Apple",
        "type": "Fruit",
        "description": "Delicious",
        "price": 1.99,
        "tax": 0.09,
    },
    {
        "name": "Car",
        "type": "Vehicle",
        "description": "Vroom",
        "price": 2999.99,
        "tax": None,
    },
    {
        "name": "Book",
        "type": "Book",
        "description": "Informative",
        "price": 5.99,
        "tax": None,
    },
    {
        "name": "Sunglasses",
        "type": "Accessories",
        "description": "Stylish",
        "price": 9.99,
        "tax": 0.1,
    },
    {
        "name": "Laptop",
        "type": "Portable",
        "description": "Powerful",
        "price": 999.99,
        "tax": None,
    },
    {
        "name": "Bicycle",
        "type": "Vehicle",
        "description": "Eco-friendly",
        "price": 199.99,
        "tax": None,
    },
    {
        "name": "Watch",
        "type": "Accessories",
        "description": "Elegant",
        "price": 19.99,
        "tax": 0.05,
    },
    {
        "name": "Headphones",
        "type": "Accessories",
        "description": "Wireless",
        "price": 49.99,
        "tax": 0.1,
    },
    {
        "name": "Backpack",
        "type": "Luggage",
        "description": "Spacious",
        "price": 29.99,
        "tax": 0.2,
    },
    {
        "name": "Camera",
        "type": "Electronics",
        "description": "High-resolution",
        "price": 499.99,
        "tax": None,
    },
    {
        "name": "T-Shirt",
        "type": "Clothing",
        "description": "Cute",
        "price": 9.99,
        "tax": None,
    },
]

mock_users = [
    {"username": "johndoe", "full_name": "John Doe"},
    {"username": "alice", "full_name": "Alice Smith"},
    {"username": "bob", "full_name": "Bob Johnson"},
]
